#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SnakeGame.Resource", IsApplication=true)]

namespace SnakeGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Apple = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Author = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BodyH = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BodyV = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Grass = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int HeadDown = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int HeadLeft = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int HeadRight = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int HeadUP = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int SnakeGame_Logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Wall = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int btnAbout = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int btnBack = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int btnGraphic = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btnNormal = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int imageView1 = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int imgAbout = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int psSeparator = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int snake = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int snake_layout = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int tvAuthor = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int tvCompany = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int tvCompanyName = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int tvName = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int txvScore = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int txvScoreG = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Graphic = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Normal = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int About = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int GphMde = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int NrmMde = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int back = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int snake_score = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
